### ISSUE TITLE
Using pop without a push

### ISSUE THREAD

**Issue by astoff** [minad/bookmark-view#1]
It doesn't seem necessary to have two types of anonymous views: those made by `bookmark-view-push` and those made by `M-x bookmark-view RET RET`. I would rather not have a keybinding for the push command, and have the pop command pop the last `V <whatever>` view.

PS: Most package names are nouns, and I can't seem to convince myself that bookmark-view refers to bookmarking of views rather than viewing of bookmarks.

**Comment by minad** [comment]
> It doesn't seem necessary to have two types of anonymous views...

I don't understand the objection here. Bookmarks are named, that's a fundamental property of them. So the `bookmark-view(-open/delete)` API etc. is there naturally. The bookmark view stack is just a convenience feature on top of that using bookmarks of a single name, since it is possible to have multiple bookmarks with the same name. We could discuss removing the stack feature altogether.

> Most package names are nouns...

bookmark-view is a noun, a "view" is a noun :)

**Comment by minad** [comment]
Do you mean that `bookmark-view RET RET` (unnamed or automatically named bookmarks) should also get the `V *stack*` name? I guess that's your point. The downside of this is that the name `V *stack*` is meaningless, while the default name used by `bookmark-view RET RET` is not.

**Comment by astoff** [comment]
> Do you mean that bookmark-view RET RET (unnamed or automatically named bookmarks) should also get the V *stack* name?

That's the idea, but concerning the names I meant the opposite: make `bookmark-view-push` and `M-x bookmark-view RET RET` both create names with a timestamp, and `bookmark-view-pop` pop the most recent automatically named bookmark.

> bookmark-view is a noun, a "view" is a noun :)

Then it's a package about viewing bookmarks!

**Comment by minad** [comment]
> both create names with a timestamp, and bookmark-view-pop pop the most recent automatically named bookmark.

Okay, I think that's a clear improvement. I will happily accept such a PR. It may still make sense to keep `bookmark-view-push` separately since it does not open the completion view. Of course it should also generate a meaningful name like `bookmark-view RET RET` then.

> Then it's a package about viewing bookmarks!

Hmm, okay I think `bookmark-view` wasn't initially planned as a "noun". I think I thought of it like this. "view" is the noun, "bookmark" is the verb. `bookmark-view`!

But the name does not really matter. We can invent a better name or prepare a PR for bookmark.el right away. But I think it is better to have this separately as a first step. If it is supposed to be merged into bookmark.el, the names should also begin with `bookmark-*`.

**Comment by minad** [comment]
One more thought - bookmark-view-push/pop accepts a name argument currently, this means you can in principle use multiple stacks. But this is not something I am really using :shrug:
